CREATE DATABASE [TaskManager]
USE [TaskManager]
GO

/****** Object:  Table [dbo].[TAREAS]    Script Date: 18/09/2024 02:56:22 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAREAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITULO] [nvarchar](100) NOT NULL,
	[DESCRIPCION] [nvarchar](500) NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


